// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using URL_Shortener.Data;

namespace URL_Shortener.Data.Migrations
{
    [DbContext(typeof(UrlModelContext))]
    partial class UrlModelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("URL_Shortener.Models.UrlModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalUrl")
                        .HasColumnName("OriginalUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .HasColumnName("Token")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UrlModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OriginalUrl = "https://www.youtube.com",
                            Token = "yt"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
